//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattingStatistic
    {
        public int Id { get; set; }
        public int TeamPlayerId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<short> Rk { get; set; }
        public Nullable<short> Gcar { get; set; }
        public Nullable<double> Gtm { get; set; }
        public string Column_7 { get; set; }
        public string Opp { get; set; }
        public string Rslt { get; set; }
        public string score { get; set; }
        public string Inngs { get; set; }
        public Nullable<short> PA { get; set; }
        public Nullable<short> AB { get; set; }
        public Nullable<short> R { get; set; }
        public Nullable<short> H { get; set; }
        public Nullable<short> C2B { get; set; }
        public Nullable<short> C3B { get; set; }
        public Nullable<short> HR { get; set; }
        public Nullable<short> RBI { get; set; }
        public Nullable<short> BB { get; set; }
        public Nullable<short> IBB { get; set; }
        public Nullable<short> SO { get; set; }
        public Nullable<short> HBP { get; set; }
        public Nullable<short> SH { get; set; }
        public Nullable<double> SF { get; set; }
        public Nullable<short> ROE { get; set; }
        public Nullable<short> GDP { get; set; }
        public Nullable<short> SB { get; set; }
        public Nullable<short> CS { get; set; }
        public Nullable<double> BA { get; set; }
        public Nullable<double> OBP { get; set; }
        public Nullable<double> SLG { get; set; }
        public Nullable<double> OPS { get; set; }
        public Nullable<short> BOP { get; set; }
        public Nullable<double> aLI { get; set; }
        public Nullable<double> WPA { get; set; }
        public Nullable<double> RE24 { get; set; }
        public string Pos { get; set; }
    
        public virtual TeamPlayer TeamPlayer { get; set; }
    }
}
