//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.TeamPlayers = new HashSet<TeamPlayer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
    
        public virtual ICollection<TeamPlayer> TeamPlayers { get; set; }
    }
}
