//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayerPeriod
    {
        public int Id { get; set; }
        public int TeamPlayerId { get; set; }
        public short FromYear { get; set; }
        public Nullable<short> ToYear { get; set; }
    
        public virtual TeamPlayer TeamPlayer { get; set; }
    }
}
