//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayer
    {
        public TeamPlayer()
        {
            this.BattingStatistics = new HashSet<BattingStatistic>();
            this.PitchingStatistics = new HashSet<PitchingStatistic>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int PlayerId { get; set; }
    
        public virtual ICollection<BattingStatistic> BattingStatistics { get; set; }
        public virtual ICollection<PitchingStatistic> PitchingStatistics { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
